# The URL the site will be built for
base_url = "https://aeruhxi.me"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola-sam"

title = "aeruhxi's blog | Pratik Chaudhary"
description = "Personal blog by Pratik Chaudhary. I write about programming and computer science."

taxonomies = [
    { name = "authors", rss = true },
]

minify_html = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "ayu-dark"

[extra]
sam_menu = [
    { text = "about", link = "/about" },
    { text = "posts", link = "/posts" },
    { text = "github", link = "https://github.com/aeruhxi" },
    { text = "twitter", link = "https://twitter.com/aeruhxi" }
]
show_word_count = false
show_reading_time = false
